language: node_js
node_js: '7'
cache: yarn
script: yarn checks && yarn build

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist/* apps@207.154.217.68:templates/current/public/
  on:
    branch: master

addons:
  ssh_known_hosts: 207.154.217.68

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"

before_deploy:
- openssl aes-256-cbc -K $encrypted_5d38d417e3d4_key -iv $encrypted_5d38d417e3d4_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
